package by.parakhnevich.keddit.controller.command;

public enum CommandName {
    NO_SUCH_COMMAND,

    LOGOUT_PAGE,
    LOGIN,
    SIGN_UP,
    REGISTRATION_PAGE,
    LOGIN_PAGE,


    //GET
    CREATE_PUBLICATION_BY_USER_PAGE,
    CREATE_PUBLICATION_BY_USER,
    PUBLICATIONS,
    COMMUNITIES,
    FOLLOWERS,
    USER_PAGE,
    COMMUNITY_PAGE,
    SEARCH_PAGE,
    //FOR_MODERATOR_AND_ADMIN
    PUBLICATIONS_ON_MODERATION
}
