package by.parakhnevich.keddit.controller.command;

public enum CommandName {
    NO_SUCH_COMMAND,

    LOGOUT,
    LOGIN,
    SIGN_UP,
    REGISTRATION_PAGE,
    LOGIN_PAGE,


    //GET
    CREATE_PUBLICATION_BY_USER_PAGE,
    CREATE_PUBLICATION_BY_USER,
    CREATE_PUBLICATION_BY_COMMUNITY_PAGE,
    CREATE_PUBLICATION_BY_COMMUNITY,
    PUBLICATIONS,
    MY_COMMUNITIES,
    FOLLOWERS,
    USER_PAGE,
    PUBLICATION_PAGE,
    ABOUT,
    COMMUNITY_PAGE,
    SEARCH_PAGE,
    SUBSCRIBE_COMMUNITY,
    SEARCH_FOLLOWER,
    SET_LIKE_PUBLICATION,
    SET_DISLIKE_PUBLICATION,
    SET_LIKE_COMMENT,
    SET_DISLIKE_COMMENT,
    //FOR_MODERATOR_AND_ADMIN
    PUBLICATIONS_ON_MODERATION
}
